name: linters

on:
  pull_request:
    paths:
      - ".github/workflows/linters.yml"
      - "src/**"
      - ".eslintrc.json"
      - "tsconfig.json"
      - "tsconfig.module.json"
      - "package.json"
      - "yarn.lock"

jobs:
  eslint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout to commit code
        uses: actions/checkout@v3

      - name: Set up Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up node_modules cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint with ESLint
        run: yarn lint
