name: tests

on:
  pull_request:
    push:
      branches:
        - master
        - stable
    paths:
      - ".github/workflows/tests.yml"
      - "src/**"
      - "tsconfig.json"
      - "tsconfig.module.json"
      - "package.json"
      - "yarn.lock"

jobs:
  ava:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout to commit code
        uses: actions/checkout@v3

      - name: Set up Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up node_modules cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build the package
        run: yarn build

      - name: Test using Ava
        run: yarn test
